image:
  file: Dockerfile

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y kali-linux-all
  - command: echo "Welcome to your Kali Linux Gitpod workspace!"

ports:
  - port: 8080
    onOpen: open-preview



